### ISSUE TITLE
CORE Asset

### ISSUE THREAD

**Issue by Leo-Dev-2004** [GameDevWS2024/Game#13]
@GameDevWS2024/design

**Comment by Malu010** [comment]
https://github.com/user-attachments/assets/939ca12d-c86e-49fd-bb23-2399ed8f8647

![Spritesheet Core (Animation)](https://github.com/user-attachments/assets/3aff9598-30ff-43e2-b086-e8848f6dc0b1)

**Comment by Malu010** [comment]
https://github.com/user-attachments/assets/e29548f6-07ae-43c7-8a75-ef350f693669

![Spritesheet Core (Animation)](https://github.com/user-attachments/assets/5e3ff0ef-9ed9-41ae-a3b3-cfcc413ac009)

**Comment by Malu010** [comment]
@GameDevWS2024/design habe das Issue reopened, damit ihr hier noch eure Meinung abgeben könnt

**Comment by Patrick-Woelfle** [comment]
Ich finde den Core sehr cool, ich glaube nur das er zu hochauflösend ist. Wenn wir in dem Styl alles andere machen dauert das echt lang, oder der Core ist so groß das er einen substantiellen Teil des Bildschirms einnimmt.

**Comment by Malu010** [comment]
Passt fürs erste so. Nach MVP schauen wir es uns nochmal an @GameDevWS2024/design
