### ISSUE TITLE
Protect Befehl

### ISSUE THREAD

**Issue by Leo-Dev-2004** [GameDevWS2024/Game#16]
Nicht bearbeiten bis es Arbeiter und Soldatentyp von #8 @Benzooos @Sc0pes gibt.

Soldatentyp followed Entity,
Sobald er in einem Radius Gegner sieht, greift er sie an.

Frage an @GameDevWS2024/design @Malu010 : 
- [x] - Wenn die Person die protected werden soll solange weiter läuft, soll / ab wann soll der Soldat der Person hinterherlaufen und aufhören den Enemy zu bekämpfen? 
- [x] - Was soll er tun nachdem er den Enemy getötet hat? 
- [x] - Soll protect dauerhaft gelten bis er auf jemand anderen gelegt wird oder gibt es einen Timer nachdem er wieder in den normalen Herumlaufemodus geht und von sich aus Gegner tötet? 
- [x] - Sollen sowohl der Arbeitertyp als auch der Soldatentyp flüchten, wenn sie geringe Lebenspunkte haben oder gibt es Unterschiede?  _- nur Arbeitertyp flüchtet_

**Comment by Patrick-Woelfle** [comment]
Das wären meine Vorschläge:
1. Arbeiter in der Nähe von Gegner in einen ängstlichen Zustand übergehen flüchten dann zurück zum Core, während Soldaten kämpfen bis entweder sie oder der Enemy tot sind. Wenn der Enemy zuerst tot ist, sucht der Soldat dann wieder  den Arbeiter, der so lange ängstlich bleibt, wie der Enemy am Leben ist oder eine neue Anweisung vom Spieler bekommt. Ich glaube das ist die einfachste Implementation die zu keinen weiteren Problemen führt, da es auch nicht sein sollte, das Arbeiter wieder zurück in Gefahr laufen.
2. Protect dauert so lange, bis ein anderer Befehl gegeben wird
3. Soldaten flüchten nicht, sondern kämpfen weiter bis sie tot sind.
 
@GameDevWS2024/design sagt Bescheid wenn ihr das anders seht
