### ISSUE TITLE
Offene Fragen zu Stärke und Häufigkeit von Enemies, Soldatentyp, Arbeitertyp

### ISSUE THREAD

**Issue by Leo-Dev-2004** [GameDevWS2024/Game#17]
- [x] Wie viele Enemies? Wie oft spawnen sie? Wo spawnen sie (häufiger)?
- [x] Wie stark sind Enemies, Allie-Soldatentyp, Allie-Arbeitertyp?
Gibt es sonst noch etwas zu beachten?
@GameDevWS2024/design

**Comment by Malu010** [comment]
Enemy-Stärke (early enemy): schnelle, starke angriffe, wenig HP. Ein Gegner sollte ca. 15% des Lebens eines Soldaten im Lauf eines Kampfes abziehen und ca 70-80% von einem Arbeitertyp.
Soldat-Stärke: mittelschnell, starke Angriffe, mittelviel HP.  Könnte das 5-fache vom HP des Gegner haben.
Arbeiter: schnell, schwache Angriffe, wenig HP. Max so viel Leben wie Gegner am Anfang

@Leo-Dev-2004 Offene Fragen zu Gegner werden beantwortet, sobald Spielverlauf geklärt ist.
@grimpoteuthis-octopoda @Patrick-Woelfle antwortet gerne auf den Kommentar, wenn ihr andere Vorstellungen habt

**Comment by Malu010** [comment]
Fragen wurden alle geklärt fürs erste. Alles weitere ist davon abhängig was bis zum MVP gecodet werden kann
