### ISSUE TITLE
geplanter Spielverlauf MVP mit aktuellem Stand

### ISSUE THREAD

**Issue by Leo-Dev-2004** [GameDevWS2024/Game#20]
- [ ] Spielverlauf der ersten 1–4 Minuten (MVP-Version):
Start (Minute 0–1): 
 - [x] 1.	Spieler erwacht neben dem Core:
 - [x] o	Spieler sieht den hellen Bereich um den Core (Kreis 1) und den leicht beleuchteten äußeren Kreis (Kreis 2).
- [x] o	Eine kurze Nachricht erklärt die Grundmechaniken: "Bleib im Licht! Schattenwesen greifen dich und deine Allies an." und führt den Player ein in die Befehle für Allies. Nach dem Lesen verschwindet das Textfeld.  @Malu010 
- [ ] 2.	Ein erster Ally (Arbeitertyp) erscheint im Lichtbereich: @Leo-Dev-2004 
- [ ] o	Der Spieler kann ihm den ersten Befehl geben, z. B. "Collect Wood" @xSouperMan 
- [ ] o	Der Ally bewegt sich zu einem markierten Holz-Objekt im äußeren Kreis, sammelt es ein, und kehrt zurück zum Core. @xSouperMan 
- [ ] o	Sobald er das Item abliefert, wird die Lichtenergie des Cores um 1 erhöht. @xSouperMan 
________________________________________
- [ ] Mittlerer Verlauf (Minute 1–3): 3. Schattenwesen spawnen und greifen an: 
- [x] •Ein Enemy taucht in der Nähe des äußeren Kreises auf, wird sichtbar, wenn er sich dem Licht nähert, und greift den Core oder Allie oder Player an. @Leo-Dev-2004 
- [ ] o	4. Ein zweiter Allie (Soldatentyp) läuft zum Core und stellt sich vor @konradbausch @Sc0pes 
- [ ] o	Textfeld sagt „Befehle dem Soldat den Core zu beschützen“, Spieler gibt das Kommando "Protect Core", um den Soldaten zu aktivieren. Das Textfeld verschwindet nach dem Lesen. @konradbausch 
- [ ] o	Der Soldat bewegt sich in den äußeren Kreis, greift das Schattenwesen automatisch an und besiegt es nach Mechaniken von #9 und #16. Könnte wie Enemycode funktionieren nur sucht es nach Gruppe Enemy. @konradbausch 
________________________________________
- [ ] Spannungsaufbau (Minute 3–4): 
Lichtbereich erweitert sich: 
- [ ] o	Wenn der Core genug Ressourcen gesammelt hat, vergrößert sich der helle Bereich leicht. @xSouperMan @Benzooos
- [ ] o	Dies erlaubt mehr Bewegungsfreiheit und Zugang zu neuen Ressourcen. @Benzooos @Sc0pes 
- [ ] o	Ein Textfeld kündigt dies als Fortschritt an: "Das Licht wächst! Sammle mehr Ressourcen, um den Core weiter zu stärken." @Benzooos @Sc0pes
- [x] o Der Allie sammelt die neue Ressource ein und bringt sie zurück zum Core. Dann (Core hat 2 Ressourcen) switched das Spiel die Szene (wie gameOver) aber nun erscheint ein Textfeld "want to play more? More to come soon!" und eine Audiodatei mit spannender Musik wird abgespielt. @Patrick-Woelfle @xSouperMan @Malu010 
____________________________________

**Comment by Leo-Dev-2004** [comment]
@GameDevWS2024/code  @GameDevWS2024/design Hier bitte kommentieren um die Checkliste zu **aktualisieren**, **verbessern**, **Vorschläge** zu machen für den **Ablauf** beim @GameDevWS2024/code Team damit unser **MVP** Bombe wird. 😊🙌

**Comment by Malu010** [comment]
Vorschlag zu "
> * [ ]  Mittlerer Verlauf (Minute 1–3): 3. Schattenwesen spawnen und greifen an:
> * [x]  •Ein Enemy taucht in der Nähe des äußeren Kreises auf, wird sichtbar, wenn er sich dem Licht nähert, und greift den Core 
"
Abbaubare Resourcen werden so geplaced, dass ein Pfad geöffnet wird, wenn abgebaut (heißt die Resourcen müssen so geplaced werden, dass Spieler gelenkt werden die "richtigen" abzubauen). Sobald der Pfad geöffnet wird, erscheint ein Schattenwesen der den Arbeiter angreift. Nachricht erscheint "ein Ally wird angegriffen. Sage deinem Soldaten "rescue" (oder was der Befehl zum helfen sein wird) damit er ihm hilft"
@grimpoteuthis-octopoda  @Patrick-Woelfle @TamedNightFury  
Ist das aus der Coding-Sicht umsetzbar in der kurzen Zeit @Leo-Dev-2004  @GameDevWS2024/code ?

**Comment by Leo-Dev-2004** [comment]
Oh mies, erst jetzt gesehen... wäre glaub nicht mehr schaffbar :/
