### ISSUE TITLE
MVP: Messages and introduction

### ISSUE THREAD

**Issue by Leo-Dev-2004** [GameDevWS2024/Game#25]
For our MVP product we need boxes that introduce the player into the game and we need a separation for the game phases. 
We also need a second allie that joins later on and needs to be introduced.

**Comment by Malu010** [comment]
@TamedNightFury  kannst du das Design für den zweiten Ally machen?

**Comment by TamedNightFury** [comment]
> @TamedNightFury kannst du das Design für den zweiten Ally machen?

Kann ich machen. Also den Arbeiter Ally dann, oder?

**Comment by Malu010** [comment]
Klare Abtrennung zwischen den Phasen werden vermutlich nicht rechtzeitig für das MVP fertig, da sie von anderen Faktoren die noch gemacht werden abhängig sind
