### ISSUE TITLE
Missing core implementation

### ISSUE THREAD

**Issue by Sc0pes** [GameDevWS2024/Game#5]
Currently the core with very basic functionality is missing which we need for implementing the Map functionality

**Comment by Leo-Dev-2004** [comment]
Ich implementiere einen simplen CORE @Sc0pes

**Comment by Benzooos** [comment]
Sind da schon dran, machen morgen früh vollends fertig. Kannst was anderes machen 👍👍

**Comment by Leo-Dev-2004** [comment]
Okay nice. Setze mich an ein Health System 👍

**Comment by Leo-Dev-2004** [comment]
Okay, mit einem eingebauten Enemy hab ich im aktuellen Health-System Branch einen Node2D CORE hinzugefügt. Müsste man beim mergen in main dann bedenken, dass in der Enemy-Scene (rechts oben im Property Editor) auch wieder die Verknüpfung zu eurem CORE hinzugefügt wird, wenn ihr auch einen habt.
