### ISSUE TITLE
Collect [Philip]: Implementiere Sammelmachanik für Ressourcen

### ISSUE THREAD

**Issue by Leo-Dev-2004** [GameDevWS2024/Game#7]
- [x] - Erstelle eine Liste von Items mit Namen und Positionen (z.B. "Kupfer", "Holz", "Metall").
- [x] - Allies suchen in der Itemliste nach der nächsten Position mit der gewünschten Ressource.
- [x] - Allies bewegen sich zur Position, sammeln das Item ein und kehren zum Core zurück.
- [x] - In GoDot: Objekt wird direkt ausgeblendet und Element aus der Itemliste entfernt.
- [x] - In Allie: Boolean (goingBack) = true und item(kupfer/holz/metall) += 1.
- [x] - In Core.cs: item(kupfer/holz/metall) += 1.
- [ ] - Wenn itemcounter > 10: vergrößere Lichtenergie des Cores.

**Comment by Leo-Dev-2004** [comment]
@xSouperMan Wie weit bist du? 👋 Brauchst Du Hilfe?

**Comment by xSouperMan** [comment]
alles easy bin dabei

> @xSouperMan Wie weit bist du? 👋 Brauchst Du Hilfe?

**Comment by Leo-Dev-2004** [comment]
Denkst du Mo/Di/Mi können wir das Feature mergen?
